FROM php:7.3-apache

# Add apache and php config for Laravel
COPY ./site.conf /etc/apache2/sites-available/site.conf
RUN ln -s /etc/apache2/sites-avaliable/site.conf /etc/apache2/sites-enabled/
RUN sed -i 's/Listen 80/Listen 8000/g' /etc/apache2/ports.conf
RUN a2dissite 000-default.conf && a2ensite site.conf && a2enmod rewrite

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy composer.lock and composer.json
#COPY composer.lock composer.json /var/www/
# Set working directory
WORKDIR /var/www
# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    mariadb-client \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libzip-dev \
    libpq-dev \
    && docker-php-ext-install opcache \
    && docker-php-ext-configure pgsql \
    && docker-php-ext-install pdo pdo_pgsql \
    && pecl install mongodb apcu && docker-php-ext-enable mongodb apcu opcache

RUN docker-php-ext-install pdo pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install gd

# Change uid and gid of apache to docker user uid/gid
RUN usermod -u 1000 www-data && groupmod -g 1000 www-data
#RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

WORKDIR /var/www/html

# Copy the PHP configuration file
COPY ./php.ini /usr/local/etc/php/
COPY . /var/www/html/

RUN service apache2 restart

RUN chown -R 1000 /var/www/html

RUN composer install --no-dev --prefer-dist --optimize-autoloader && \
    composer clear-cache

#creating env file
RUN touch .env
RUN echo "APP_NAME=Curriki" >> .env
RUN echo "APP_ENV=local" >> .env
RUN echo "APP_KEY=" >> .env
RUN echo "APP_DEBUG=true" >> .env
RUN echo "APP_URL=" >> .env
RUN echo "FRONT_END_URL=" >> .env
RUN echo "LOG_CHANNEL=stack" >> .env
RUN echo "DB_CONNECTION=pgsql" >> .env
RUN echo "DB_HOST=" >> .env
RUN echo "DB_PORT=" >> .env
RUN echo "DB_DATABASE=" >> .env
RUN echo "DB_USERNAME=" >> .env
RUN echo "DB_PASSWORD=" >> .env
RUN echo "BROADCAST_DRIVER=log" >> .env
RUN echo "CACHE_DRIVER=file" >> .env
RUN echo "QUEUE_CONNECTION=sync" >> .env
RUN echo "SESSION_DRIVER=file" >> .env
RUN echo "SESSION_LIFETIME=120" >> .env
RUN echo "REDIS_HOST=127.0.0.1" >> .env
RUN echo "REDIS_PASSWORD=null" >> .env
RUN echo "REDIS_PORT=6379" >> .env
RUN echo "MAIL_MAILER=smtp" >> .env
RUN echo "MAIL_HOST=smtp.mailtrap.io" >> .env
RUN echo "MAIL_PORT=2525" >> .env
RUN echo "MAIL_USERNAME=null" >> .env
RUN echo "MAIL_PASSWORD=null" >> .env
RUN echo "MAIL_ENCRYPTION=null" >> .env
RUN echo "MAIL_FROM_ADDRESS=null" >> .env
RUN echo "MAIL_FROM_NAME="${APP_NAME}"" >> .env
RUN echo "AWS_ACCESS_KEY_ID=" >> .env
RUN echo "AWS_SECRET_ACCESS_KEY=" >> .env
RUN echo "AWS_DEFAULT_REGION=us-east-1" >> .env
RUN echo "AWS_BUCKET=" >> .env
RUN echo "PUSHER_APP_ID=" >> .env
RUN echo "PUSHER_APP_KEY=" >> .env
RUN echo "PUSHER_APP_SECRET=" >> .env
RUN echo "PUSHER_APP_CLUSTER=mt1" >> .env
RUN echo "MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"" >> .env
RUN echo "MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"" >> .env
RUN echo "MATTERMOST_SERVER=default" >> .env
RUN echo "MATTERMOST_HOST=" >> .env
RUN echo "MATTERMOST_LOGIN=" >> .env
RUN echo "MATTERMOST_LOGIN=" >> .env
RUN echo "MATTERMOST_PASSWORD=" >> .env
RUN echo "MATTERMOST_DEFAULT_TEAM_ID=" >> .env
RUN echo "GAPI_CLASSROOM_CREDENTIALS=" >> .env
RUN echo "GAPI_CLIENT_ID=" >> .env

RUN php artisan config:cache
