namespace: pilots
createClusterIssuer: false
image:
  apirepo: quay.io/curriki/api:studio
  cronrepo: quay.io/curriki/cron:studio
  clientrepo: quay.io/curriki/client:studio
  tsugirepo: quay.io/curriki/tsugi:studio
  traxrepo: quay.io/curriki/trax:latest
nfsServer: 139.144.231.192
host: studio.curriki.org
volumePath: /mnt/pilotsStorage
traxStorage: /mnt/pilotsTraxStorage
clientEnvConfigMap:
  REACT_APP_PEXEL_API: "563492ad6f91700001000001155d7b75f5424ea694b81ce9f867dddf"
  REACT_APP_API_URL: "https://studio.curriki.org/api/api"
  REACT_APP_RESOURCE_URL: "https://studio.curriki.org/api"
  REACT_APP_GOOGLE_CAPTCHA: "6LdImbgZAAAAAN4s1eEi53-ul7uJfLONrFuBcKS0"
  REACT_APP_GAPI_CLIENT_ID: "898143939834-9ioui2i9ghgrmcgmgtg0h6rsf83d0t0c.apps.googleusercontent.com"
  REACT_APP_HUBSPOT: "7874555"
  REACT_APP_API_VERSION: "v1"
  REACT_APP_H5P_KEY: "B6TFsmFD5TLZaWCAYZ91ly0D2We0xjLAtRmBJzQ"
  REACT_APP_TSUGI_SERVER_URL: "https://studio-tsugi.curriki.org/mod/curriki/"
  REACT_APP_SHARED_PROJECT_DEMO_USER: "demoaccount@gmail.com"
  REACT_APP_SHARED_PROJECT_DEMO_PASS: "Qwerty123"
  REACT_APP_SHARED_PROJECT_USERID: "1608"
clientEnvLocalConfigMap: |
  REACT_APP_PEXEL_API=563492ad6f91700001000001155d7b75f5424ea694b81ce9f867dddf
  REACT_APP_API_URL=https://studio.curriki.org/api/api
  REACT_APP_RESOURCE_URL=https://studio.curriki.org/api
  REACT_APP_GOOGLE_CAPTCHA=6LdImbgZAAAAAN4s1eEi53-ul7uJfLONrFuBcKS0
  REACT_APP_GAPI_CLIENT_ID=898143939834-9ioui2i9ghgrmcgmgtg0h6rsf83d0t0c.apps.googleusercontent.com
  REACT_APP_HUBSPOT=7874555
  REACT_APP_API_VERSION=v1
  REACT_APP_H5P_KEY=B6TFsmFD5TLZaWCAYZ91ly0D2We0xjLAtRmBJzQ
  REACT_APP_TSUGI_SERVER_URL=https://studio-tsugi.curriki.org/mod/curriki/
  REACT_APP_SHARED_PROJECT_DEMO_USER=demoaccount@gmail.com
  REACT_APP_SHARED_PROJECT_DEMO_PASS=Qwerty123
  REACT_APP_SHARED_PROJECT_USERID=1608

clientRuntimeConfig: |
    window.__RUNTIME_CONFIG__ = { "REACT_APP_PEXEL_API": "563492ad6f91700001000001155d7b75f5424ea694b81ce9f867dddf", "REACT_APP_API_URL": "https://studio.curriki.org/api/api", "REACT_APP_RESOURCE_URL": "https://studio.curriki.org/api", "REACT_APP_GOOGLE_CAPTCHA": "6LdImbgZAAAAAN4s1eEi53-ul7uJfLONrFuBcKS0", "REACT_APP_GAPI_CLIENT_ID": "898143939834-9ioui2i9ghgrmcgmgtg0h6rsf83d0t0c.apps.googleusercontent.com", "REACT_APP_HUBSPOT": "7874555", "REACT_APP_API_VERSION": "v1", "REACT_APP_H5P_KEY": "B6TFsmFD5TLZaWCAYZ91ly0D2We0xjLAtRmBJzQ", "REACT_APP_TSUGI_SERVER_URL": "https://studio-tsugi.curriki.org/mod/curriki/", "REACT_APP_SHARED_PROJECT_DEMO_USER": "demoaccount@gmail.com", "REACT_APP_SHARED_PROJECT_DEMO_PASS": "Qwerty123", "REACT_APP_SHARED_PROJECT_USERID": "1608" };

currikiTsugiHost: |
  <?php
    define('CURRIKI_STUDIO_HOST', 'https://studio.curriki.org');

ingHosts:
  - studio.curriki.org
  - studio-trax.curriki.org
  - studio-tsugi.curriki.org
ingRules:
  - host: studio.curriki.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: client-svc
            port:
              number: 80
  - host: studio-trax.curriki.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: trax-svc
            port:
              number: 80
  - host: studio-tsugi.curriki.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tsugi-svc
            port:
              number: 80


