namespace: prod
image:
  apirepo: quay.io/curriki/api:prod
  cronrepo: quay.io/curriki/cron:prod
  tsugirepo: quay.io/curriki/tsugi:prod
  traxrepo: quay.io/curriki/trax:latest
nfsServer: 139.144.231.192
host: my.currikistudio.org
volumePath: /mnt/prodStorage
traxStorage: /mnt/prodTraxStorage
currikiTsugiHost: |
  <?php
    define('CURRIKI_STUDIO_HOST', 'https://my.currikistudio.org');

ingHosts:
  - my.currikistudio.org
  - trax.currikistudio.org
  - tsugi.currikistudio.org
ingRules:
  - host: my.currikistudio.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: client-svc
            port:
              number: 80
  - host: trax.currikistudio.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: trax-svc
            port:
              number: 80
  - host: tsugi.currikistudio.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tsugi-svc
            port:
              number: 80

    