namespace: prod
image:
  apirepo: quay.io/curriki/api:prod
  cronrepo: quay.io/curriki/cron:prod
  clientrepo: quay.io/curriki/client:kube-prod
  tsugirepo: quay.io/curriki/tsugi:prod
  traxrepo: quay.io/curriki/trax:prod
nfsServer: 139.144.231.192
host: my.currikistudio.org
volumePath: /mnt/prodStorage
traxStorage: /mnt/prodTraxStorage
clientEnvConfigMap:
  REACT_APP_PEXEL_API: "563492ad6f91700001000001155d7b75f5424ea694b81ce9f867dddf"
  REACT_APP_API_URL: "https://my.currikistudio.org/api/api"
  REACT_APP_RESOURCE_URL: "https://my.currikistudio.org/api"
  REACT_APP_GOOGLE_CAPTCHA: "6LdImbgZAAAAAN4s1eEi53-ul7uJfLONrFuBcKS0"
  REACT_APP_GAPI_CLIENT_ID: "898143939834-9ioui2i9ghgrmcgmgtg0h6rsf83d0t0c.apps.googleusercontent.com"
  REACT_APP_HUBSPOT: "7874555"
  REACT_APP_API_VERSION: "v1"
  REACT_APP_H5P_KEY: "B6TFsmFD5TLZaWCAYZ91ly0D2We0xjLAtRmBJzQ"
  REACT_APP_TSUGI_SERVER_URL: "https://tsugi.currikistudio.org/mod/curriki/"
  REACT_APP_SHARED_PROJECT_DEMO_USER: "demoaccount@gmail.com"
  REACT_APP_SHARED_PROJECT_DEMO_PASS: "Qwerty123"
  REACT_APP_SHARED_PROJECT_USERID: "726"
  REACT_APP_SAFELEARN_AUTH: "https://api.v10.learnsafe.com/accounts/AC5771e791affd4176966bf63c846c8701/integrators/auth/token"
  REACT_APP_SAFELEARN_CHECK: "https://api.v10.learnsafe.com/accounts/AC5771e791affd4176966bf63c846c8701/integrators/content/check"
  REACT_APP_SAFELEARN_APPLICATIONNAME: "null"
  REACT_APP_SAFELEARN_UNITPATH: "null"
  REACT_APP_SAFELEARN_KEY: "null"
  REACT_APP_STEMULI: "true"
  REACT_DOMAIN_URL: "https://my.currikistudio.org/"

clientEnvLocalConfigMap: |
    REACT_APP_PEXEL_API=563492ad6f91700001000001155d7b75f5424ea694b81ce9f867dddf
    REACT_APP_API_URL=https://my.currikistudio.org/api/api
    REACT_APP_RESOURCE_URL=https://my.currikistudio.org/api
    REACT_APP_GOOGLE_CAPTCHA=6LdImbgZAAAAAN4s1eEi53-ul7uJfLONrFuBcKS0
    REACT_APP_GAPI_CLIENT_ID=898143939834-9ioui2i9ghgrmcgmgtg0h6rsf83d0t0c.apps.googleusercontent.com
    REACT_APP_HUBSPOT=7874555
    REACT_APP_API_VERSION=v1
    REACT_APP_H5P_KEY=B6TFsmFD5TLZaWCAYZ91ly0D2We0xjLAtRmBJzQ
    REACT_APP_TSUGI_SERVER_URL=https://tsugi.currikistudio.org/mod/curriki/
    REACT_APP_SHARED_PROJECT_DEMO_USER=demoaccount@gmail.com
    REACT_APP_SHARED_PROJECT_DEMO_PASS=Qwerty123
    REACT_APP_SHARED_PROJECT_USERID=726
    REACT_APP_SAFELEARN_AUTH=https://api.v10.learnsafe.com/accounts/AC5771e791affd4176966bf63c846c8701/integrators/auth/token
    REACT_APP_SAFELEARN_CHECK=https://api.v10.learnsafe.com/accounts/AC5771e791affd4176966bf63c846c8701/integrators/content/check
    REACT_APP_SAFELEARN_APPLICATIONNAME=null
    REACT_APP_SAFELEARN_UNITPATH=null
    REACT_APP_SAFELEARN_KEY=null
    REACT_APP_STEMULI=true
    REACT_DOMAIN_URL=https://my.currikistudio.org/
clientRuntimeConfig: |
    window.__RUNTIME_CONFIG__ = { "REACT_APP_PEXEL_API": "563492ad6f91700001000001155d7b75f5424ea694b81ce9f867dddf", "REACT_APP_API_URL": "https://my.currikistudio.org/api/api", "REACT_APP_RESOURCE_URL": "https://my.currikistudio.org/api", "REACT_APP_GOOGLE_CAPTCHA": "6LdImbgZAAAAAN4s1eEi53-ul7uJfLONrFuBcKS0", "REACT_APP_GAPI_CLIENT_ID": "898143939834-9ioui2i9ghgrmcgmgtg0h6rsf83d0t0c.apps.googleusercontent.com", "REACT_APP_HUBSPOT": "7874555", "REACT_APP_API_VERSION": "v1", "REACT_APP_H5P_KEY": "B6TFsmFD5TLZaWCAYZ91ly0D2We0xjLAtRmBJzQ", "REACT_APP_TSUGI_SERVER_URL": "https://tsugi.currikistudio.org/mod/curriki/", "REACT_APP_SHARED_PROJECT_DEMO_USER": "demoaccount@gmail.com", "REACT_APP_SHARED_PROJECT_DEMO_PASS": "Qwerty123", "REACT_APP_SHARED_PROJECT_USERID": "726", "REACT_APP_SAFELEARN_AUTH": "https://api.v10.learnsafe.com/accounts/AC5771e791affd4176966bf63c846c8701/integrators/auth/token", "REACT_APP_SAFELEARN_CHECK": "https://api.v10.learnsafe.com/accounts/AC5771e791affd4176966bf63c846c8701/integrators/content/check", "REACT_APP_SAFELEARN_APPLICATIONNAME": "null", "REACT_APP_SAFELEARN_UNITPATH": "null", "REACT_APP_SAFELEARN_KEY": "null", "REACT_APP_STEMULI": "true", "REACT_DOMAIN_URL": "https://my.currikistudio.org/" };

currikiTsugiHost: |
  <?php
    define('CURRIKI_STUDIO_HOST', 'https://my.currikistudio.org');

ingHosts:
  - my.currikistudio.org
  - trax.currikistudio.org
  - tsugi.currikistudio.org
ingRules:
  - host: my.currikistudio.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: client-svc
            port:
              number: 80
  - host: trax.currikistudio.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: trax-svc
            port:
              number: 80
  - host: tsugi.currikistudio.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tsugi-svc
            port:
              number: 80

    