SITE_NAME: "{{ SITE_NAME }}"

LANGUAGE_NAME: "{{ LANGUAGE_NAME }}"
SITE_PATH_enUS: "{{ SITE_SRC }}"
DOMAIN_NAME: "{{ DOMAIN_NAME }}"
DOMAIN_PACKAGE_NAME: "{{ SITE_JAVA_PACKAGE }}"
SUFFIX_SRC_MAIN_JAVA: "{{ SUFFIX_SRC_MAIN_JAVA }}"
SUFFIX_SRC_GEN_JAVA: "{{ SUFFIX_SRC_GEN_JAVA }}"
RELATIVE_PATHS_TO_WATCH: "{{ RELATIVE_PATHS_TO_WATCH }}"

JDBC_HOST: "{{ JDBC_HOST }}"
JDBC_PORT: {{ JDBC_PORT }}
JDBC_DATABASE: "{{ JDBC_DATABASE }}"
JDBC_USERNAME: "{{ JDBC_USERNAME }}"
JDBC_PASSWORD: "{{ JDBC_PASSWORD }}"
SITE_HOST_NAME: "{{ SITE_HOST_NAME }}"
SITE_BASE_URL: "{{ SITE_BASE_URL }}"
AUTH_HOST_NAME: "{{ AUTH_HOST_NAME }}"
AUTH_PORT: {{ AUTH_PORT }}
AUTH_SSL: {{ AUTH_SSL | lower }}
AUTH_SSL_REQUIRED: {{ AUTH_SSL_REQUIRED }}
AUTH_REALM: "{{ AUTH_REALM }}"
AUTH_RESOURCE: "{{ AUTH_RESOURCE }}"
AUTH_SECRET: "{{ AUTH_SECRET }}"
AUTH_URL: "{{ AUTH_URL }}"
AUTH_TOKEN_URI: "{{ AUTH_TOKEN_URI }}"
SITE_PORT: {{ SITE_PORT }}
SOLR_URL: "{{ SOLR_URL }}"
SOLR_URL_COMPUTATE: "{{ SOLR_URL_COMPUTATE }}"
API_CONTACT_EMAIL: "{{ EMAIL_FROM }}"
SITE_ZONE: "{{ SITE_ZONE }}"
SITE_LOCALE: en-US
STATIC_BASE_URL: "{{ STATIC_BASE_URL }}"
STATIC_PATH: "{{ STATIC_PATH }}"
TEMPLATE_PATH: "{{ TEMPLATE_PATH }}"
EMAIL_HOST: {{ EMAIL_HOST }}
EMAIL_PORT: {{ EMAIL_PORT }}
EMAIL_SSL: {{ EMAIL_SSL }}
EMAIL_AUTH: {{ EMAIL_AUTH }}
EMAIL_USERNAME: {{ EMAIL_USERNAME }}
EMAIL_PASSWORD: {{ EMAIL_PASSWORD }}
EMAIL_FROM: {{ EMAIL_FROM }}
EMAIL_ADMIN: {{ EMAIL_ADMIN }}
# Set the userKey of the user creating an object in the database. 
ENABLE_USER_KEY: {{ ENABLE_USER_KEY }}
# Set the sessionId of the user session creating an object in the database. 
ENABLE_SESSION_ID: {{ ENABLE_SESSION_ID }}
# Enable an object in the database to be deleted. 
ENABLE_DELETED: {{ ENABLE_DELETED }}
# Enable an object in the database to be archived. 
ENABLE_ARCHIVED: {{ ENABLE_ARCHIVED }}
# Enable data import in the site. 
ENABLE_IMPORT_DATA: {{ ENABLE_IMPORT_DATA }}

# The Auth roles required to be an admin in the site. 
AUTH_ROLES_ADMIN: {{ AUTH_ROLES_ADMIN }}
# The Auth roles required to add and modify SiteUser records. 
AUTH_ROLES_REQUIRED_SequenceRun: {{ AUTH_ROLES_REQUIRED_SiteUser }}
