---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
      - name: api
        image: quay.io/curriki/api:stage
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: api-env
          mountPath: /var/www/html/.env
          subPath: .env
        - name: nfs-volume
          mountPath: /var/www/html/storage
        envFrom:
        - secretRef:
            name: api-env
        resources:
          limits:
            cpu: 600m
            memory: 1500Mi
          requests:
            cpu: 350m
            memory: 800Mi
        command:
        - /bin/sh
        - -c
        - |
          apache2ctl -D FOREGROUND
      volumes:
      - name: api-env
        secret:
          secretName: api-env
      - name: nfs-volume
        nfs:
          server: 192.46.218.167
          path: /mnt/storage
          readOnly: no


---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-api

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cron
  labels:
    app: {{ .Release.Name }}-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cron
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cron
    spec:
      containers:
      - name: api
        image: quay.io/curriki/cron:stage
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: api-env
          mountPath: /var/www/html/.env
          subPath: .env
        - name: nfs-volume
          mountPath: /var/www/html/storage
        envFrom:
        - secretRef:
            name: api-env
        command:
        - /bin/sh
        - -c
        - |
          apache2ctl -D FOREGROUND
      volumes:
      - name: api-env
        secret:
          secretName: api-env
      - name: nfs-volume
        nfs:
          server: 192.46.218.167
          path: /mnt/storage
          readOnly: no



---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  template:
    spec:
      containers:
      - name: migration
        image: quay.io/curriki/api:stage
        imagePullPolicy: Always
        command: 
        - /bin/sh
        - -c
        - php /var/www/html/artisan migrate --force
        volumeMounts:
        - name: api-env
          mountPath: /var/www/html/.env
          subPath: .env
        - name: nfs-volume
          mountPath: /var/www/html/storage
        envFrom:
        - secretRef:
            name: api-env
      restartPolicy: Never
      volumes:
      - name: api-env
        secret:
          secretName: api-env
      - name: nfs-volume
        nfs:
          server: 192.46.218.167
          path: /mnt/storage
          readOnly: no
  backoffLimit: 4


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-queue
  labels:
    app: {{ .Release.Name }}-queue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-queue
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-queue
    spec:
      containers:
      - name: queue
        image: quay.io/curriki/api:stage
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command: 
        - /bin/sh
        - -c
        - php /var/www/html/artisan queue:work --timeout=0
        volumeMounts:
        - name: api-env
          mountPath: /var/www/html/.env
          subPath: .env
        - name: nfs-volume
          mountPath: /var/www/html/storage
        envFrom:
        - secretRef:
            name: api-env
      volumes:
      - name: api-env
        secret:
          secretName: api-env
      - name: nfs-volume
        nfs:
          server: 192.46.218.167
          path: /mnt/storage
          readOnly: no