apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      {{- with .Values.ingHosts }}
        {{- toYaml . | nindent 6}}
      {{- end}}
      secretName: letsencrypt
  rules:
  {{- with .Values.ingRules }}
    {{- toYaml . | nindent 4}}
  {{- end}}