---
# Label: ansible_project_keystore
# Title: create the Ansible template for the project keystore secret in OpenShift
# Mission: create the Ansible template for the project keystore secret in OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

apiVersion: v1
kind: Secret
type: Opaque
stringData:
  {{SSL_PROPERTIES_FILENAME}}: |-
    keystore-path={{SSL_JKS_PATH}}
    keystore-alias={{SSL_ALIAS}}
    keystore-storepass={{SSL_JKS_PASSWORD}}
    keystore-keypass={{SSL_JKS_PASSWORD}}
data:
  {{SSL_JKS_FILENAME}}: >-
    {{SSL_JKS_BASE64}}
